# If this file is modified, you must also rebuild the dev container as we pre-bake the west projects into the image.
# See docs/pushing-new-dev-container-image.md for instructions.
manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.2.0
      import:
        name-allowlist:
          - cmsis_6
          - hal_nxp
          - hal_stm32
          - nanopb

    - name: Arduino-Core-Zephyr
      path: modules/lib/Arduino-Zephyr-API
      revision: main
      url: https://github.com/zephyrproject-rtos/arduino-core-zephyr
