/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "clover.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Request, Request, AUTO)


PB_BIND(Response, Response, AUTO)


PB_BIND(SubscribeDataStreamRequest, SubscribeDataStreamRequest, AUTO)


PB_BIND(IsNotAbortedRequest, IsNotAbortedRequest, AUTO)


PB_BIND(IdentifyClientRequest, IdentifyClientRequest, AUTO)


PB_BIND(ConfigureAnalogSensorsRequest, ConfigureAnalogSensorsRequest, AUTO)


PB_BIND(AnalogSensorConfig, AnalogSensorConfig, AUTO)


PB_BIND(ResetValvePositionRequest, ResetValvePositionRequest, AUTO)


PB_BIND(PowerOnValveRequest, PowerOnValveRequest, AUTO)


PB_BIND(PowerOffValveRequest, PowerOffValveRequest, AUTO)


PB_BIND(AbortRequest, AbortRequest, AUTO)


PB_BIND(HaltRequest, HaltRequest, AUTO)


PB_BIND(UnprimeRequest, UnprimeRequest, AUTO)


PB_BIND(CalibrateValveRequest, CalibrateValveRequest, AUTO)


PB_BIND(LoadValveSequenceRequest, LoadValveSequenceRequest, AUTO)


PB_BIND(StartValveSequenceRequest, StartValveSequenceRequest, AUTO)


PB_BIND(LoadThrustSequenceRequest, LoadThrustSequenceRequest, AUTO)


PB_BIND(StartThrustSequenceRequest, StartThrustSequenceRequest, AUTO)


PB_BIND(ControlTrace, ControlTrace, AUTO)


PB_BIND(Segment, Segment, AUTO)


PB_BIND(LinearSegment, LinearSegment, AUTO)


PB_BIND(SineSegment, SineSegment, AUTO)


PB_BIND(DataPacket, DataPacket, 2)


PB_BIND(ControllerTiming, ControllerTiming, AUTO)


PB_BIND(ValveStatus, ValveStatus, AUTO)


PB_BIND(AnalogSensorReadings, AnalogSensorReadings, AUTO)


PB_BIND(IdleData, IdleData, AUTO)


PB_BIND(AbortData, AbortData, AUTO)


PB_BIND(ValveCalibrationData, ValveCalibrationData, AUTO)


PB_BIND(ValveSequenceData, ValveSequenceData, AUTO)


PB_BIND(ThrustSequenceData, ThrustSequenceData, AUTO)













