/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_CLOVER_PB_H_INCLUDED
#define PB_CLOVER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ClientType {
    ClientType_UNKNOWN_CLIENT = 1,
    ClientType_GNC = 2,
    ClientType_DAQ = 3
} ClientType;

typedef enum _TCType {
    TCType_UNKNOWN_TC_TYPE = 0,
    TCType_K_TYPE = 1,
    TCType_T_TYPE = 2
} TCType;

typedef enum _AnalogSensor {
    AnalogSensor_UNKNOWN_ANALOG_SENSOR = 0,
    /* Vehicle pressurant */
    AnalogSensor_PT001 = 1,
    AnalogSensor_PT002 = 2,
    AnalogSensor_PT003 = 3,
    AnalogSensor_PT004 = 4,
    AnalogSensor_PT005 = 5,
    /* Vehicle fuel side */
    AnalogSensor_PT101 = 6,
    /* Vehicle LOx side */
    AnalogSensor_PT201 = 7,
    /* Engine */
    AnalogSensor_PTF1 = 8,
    AnalogSensor_PTF2 = 9,
    AnalogSensor_PTO1 = 10,
    AnalogSensor_PTC1 = 11,
    AnalogSensor_PTC2 = 12,
    /* TCs */
    AnalogSensor_TC001 = 13,
    AnalogSensor_TC101 = 14,
    AnalogSensor_TC102 = 15,
    AnalogSensor_TCF1 = 16,
    AnalogSensor_TCO1 = 17,
    /* GSE pressurant */
    AnalogSensor_PTG001 = 18,
    AnalogSensor_PTG002 = 19,
    /* GSE LOx */
    AnalogSensor_PTG101 = 20,
    /* Hornet */
    AnalogSensor_BATTERY_VOLTAGE = 21
} AnalogSensor;

typedef enum _Valve {
    Valve_UNKNOWN_VALVE = 0,
    Valve_FUEL = 1,
    Valve_LOX = 2
} Valve;

/* Controller State definition */
typedef enum _SystemState {
    SystemState_STATE_UNKNOWN = 0,
    SystemState_STATE_IDLE = 1,
    SystemState_STATE_CALIBRATE_VALVE = 2,
    SystemState_STATE_VALVE_PRIMED = 3,
    SystemState_STATE_VALVE_SEQ = 4,
    SystemState_STATE_THRUST_PRIMED = 5,
    SystemState_STATE_THRUST_SEQ = 6,
    SystemState_STATE_ABORT = 7
} SystemState;

/* Struct definitions */
/* Successful if err is missing. */
typedef struct _Response {
    pb_callback_t err;
} Response;

/* Subscribe client IP to data stream. */
typedef struct _SubscribeDataStreamRequest {
    char dummy_field;
} SubscribeDataStreamRequest;

/* Errors if the state is ABORT. Otherwise, returns OK. */
typedef struct _IsNotAbortedRequest {
    char dummy_field;
} IsNotAbortedRequest;

/* Names client. */
typedef struct _IdentifyClientRequest {
    ClientType client;
} IdentifyClientRequest;

/* Configure analog inputs as PTs or TCs. Should be called early in
 program lifetime to ensure analog sensor readings get populated. */
typedef struct _ConfigureAnalogSensorsRequest {
    pb_callback_t configs;
} ConfigureAnalogSensorsRequest;

/* Either all pt_* fields must be set, or all tc_* fields must be set, or all raw_* fields must be set. */
typedef struct _AnalogSensorConfig {
    /* Sensor input number, corresponds to an ADC and its channel. Set in devicetree. */
    uint32_t channel;
    AnalogSensor assignment;
    bool has_pt_range_psig;
    float pt_range_psig;
    bool has_pt_bias_psig;
    float pt_bias_psig;
    bool has_tc_type;
    TCType tc_type;
    bool has_raw_range_v;
    float raw_range_v;
    bool has_raw_bias_v;
    float raw_bias_v;
} AnalogSensorConfig;

/* Reset the valve's position. */
typedef struct _ResetValvePositionRequest {
    Valve valve;
    float new_pos_deg;
} ResetValvePositionRequest;

/* Turn on stepper motor. */
typedef struct _PowerOnValveRequest {
    Valve valve;
} PowerOnValveRequest;

/* Turn off stepper motor. */
typedef struct _PowerOffValveRequest {
    Valve valve;
} PowerOffValveRequest;

/* Abort an active control sequence into a safe state. */
typedef struct _AbortRequest {
    char dummy_field;
} AbortRequest;

/* Halt all actuators. */
typedef struct _HaltRequest {
    char dummy_field;
} HaltRequest;

/* Unprime a request. */
typedef struct _UnprimeRequest {
    char dummy_field;
} UnprimeRequest;

/* Enter valve calibration mode. */
typedef struct _CalibrateValveRequest {
    Valve valve;
} CalibrateValveRequest;

/* Start a loaded valve motor sequence. */
typedef struct _StartValveSequenceRequest {
    char dummy_field;
} StartValveSequenceRequest;

/* Start a loaded thrust sequence. */
typedef struct _StartThrustSequenceRequest {
    char dummy_field;
} StartThrustSequenceRequest;

/* Control sequences */
typedef struct _ControlTrace {
    uint32_t total_time_ms;
    pb_callback_t segments;
} ControlTrace;

/* Load a valve motor sequence. At least one trace must be set. */
typedef struct _LoadValveSequenceRequest {
    bool has_fuel_trace_deg;
    ControlTrace fuel_trace_deg;
    bool has_lox_trace_deg;
    ControlTrace lox_trace_deg;
} LoadValveSequenceRequest;

/* Load a thrust sequence. */
typedef struct _LoadThrustSequenceRequest {
    ControlTrace thrust_trace_lbf;
} LoadThrustSequenceRequest;

/* Every request sent to the server is an instance of this parent Request. The server then examines the payload to
 determine the exact command specified.
 next tag: 22 */
typedef struct _Request {
    pb_size_t which_payload;
    union _Request_payload {
        SubscribeDataStreamRequest subscribe_data_stream;
        /* Actuators */
        ResetValvePositionRequest reset_valve_position;
        IdentifyClientRequest identify_client;
        /* Transitions IDLE -> CALIBRATE_VALVE */
        CalibrateValveRequest calibrate_valve;
        /* Transitions (VALVE_SEQ, THRUST_SEQ) -> ABORT */
        AbortRequest abort;
        /* Transitions (CALIBRATE_VALVE, VALVE_SEQ, THRUST_SEQ, ABORT) -> IDLE */
        HaltRequest halt;
        /* Transitions (VALVE_PRIMED, THRUST_PRIMED) -> IDLE */
        UnprimeRequest unprime;
        /* Transitions IDLE -> VALVE_PRIMED */
        LoadValveSequenceRequest load_valve_sequence;
        /* Transitions IDLE -> THRUST_PRIMED */
        LoadThrustSequenceRequest load_thrust_sequence;
        /* Transitions VALVE_PRIMED -> VALVE_SEQ */
        StartValveSequenceRequest start_valve_sequence;
        /* Transiitons THRUST_PRIMED -> THRUST_SEQ */
        StartThrustSequenceRequest start_thrust_sequence;
        PowerOffValveRequest power_off_valve;
        PowerOnValveRequest power_on_valve;
        IsNotAbortedRequest is_not_aborted_request;
        /* Sensors */
        ConfigureAnalogSensorsRequest configure_analog_sensors;
    } payload;
} Request;

typedef struct _LinearSegment {
    float start_val;
    float end_val;
} LinearSegment;

typedef struct _SineSegment {
    float offset;
    float amplitude;
    float period;
    float phase_deg;
} SineSegment;

typedef struct _Segment {
    uint32_t start_ms;
    uint32_t length_ms;
    pb_size_t which_type;
    union _Segment_type {
        LinearSegment linear;
        SineSegment sine;
    } type;
} Segment;

/* Stats on controller and sensor execution times. */
typedef struct _ControllerTiming {
    float controller_tick_time_ns;
    float analog_sensors_sense_time_ns;
    float lidar_sense_time_ns;
} ControllerTiming;

typedef struct _ValveStatus {
    float target_pos_deg;
    float driver_setpoint_pos_deg;
    float encoder_pos_deg;
    bool is_on;
} ValveStatus;

/* PTs are in psig, TCs are in deg C, raw are in volts. */
typedef struct _AnalogSensorReadings {
    /* Vehicle pressurant */
    bool has_pt001;
    float pt001;
    bool has_pt002;
    float pt002;
    bool has_pt003;
    float pt003;
    bool has_pt004;
    float pt004;
    bool has_pt005;
    float pt005;
    /* Vehicle fuel side */
    bool has_pt101;
    float pt101;
    /* Vehicle LOx side */
    bool has_pt201;
    float pt201;
    /* Engine */
    bool has_ptf1;
    float ptf1;
    bool has_ptf2;
    float ptf2;
    bool has_pto1;
    float pto1;
    bool has_ptc1;
    float ptc1;
    bool has_ptc2;
    float ptc2;
    /* TCs */
    bool has_tc001;
    float tc001;
    bool has_tc101;
    float tc101;
    bool has_tc102;
    float tc102;
    bool has_tcf1;
    float tcf1;
    bool has_tco1;
    float tco1;
    /* GSE pressurant */
    bool has_ptg001;
    float ptg001;
    bool has_ptg002;
    float ptg002;
    /* GSE LOx */
    bool has_ptg101;
    float ptg101;
    /* Hornet */
    bool has_battery_voltage;
    float battery_voltage;
} AnalogSensorReadings;

typedef struct _IdleData {
    char dummy_field;
} IdleData;

typedef struct _AbortData {
    char dummy_field;
} AbortData;

typedef struct _ValveCalibrationData {
    bool fuel_found_hardstop;
    float fuel_hardstop_pos;
    bool lox_found_hardstop;
    float lox_hardstop_pos;
    int32_t cal_phase;
    int32_t rep_count;
    float fuel_err;
    float lox_err;
} ValveCalibrationData;

typedef struct _ValveSequenceData {
    char dummy_field;
} ValveSequenceData;

/* TODO */
typedef struct _ThrustSequenceData {
    float predicted_thrust;
    float predicted_of;
    float mdot_fuel;
    float mdot_lox;
    float target_thrust;
    float thrust_error;
    float change_alpha_cmd;
    float clamped_change_alpha_cmd;
    float alpha;
    float thrust_from_alpha;
    float fuel_valve_cmd;
    float lox_valve_cmd;
} ThrustSequenceData;

/* next tag: 21 */
typedef struct _DataPacket {
    /* Time since chip start in nanoseconds. */
    uint64_t time_ns;
    /* Size of pending queue of data packets to send. */
    uint32_t data_queue_size;
    /* Actuators */
    ValveStatus fuel_valve;
    ValveStatus lox_valve;
    /* Current controller state */
    SystemState state;
    /* Counts up for each data packet sent. */
    uint64_t sequence_number;
    pb_size_t which_state_data;
    union _DataPacket_state_data {
        /* VALVE_CALIBRATION */
        ValveCalibrationData valve_calibration_data;
        /* VALVE_SEQ */
        ValveSequenceData valve_sequence_data;
        /* THRUST_SEQ */
        ThrustSequenceData thrust_sequence_data;
        /* IDLE, VALVE_PRIMED, THRUST_PRIMED */
        IdleData idle_data;
        /* ABORT */
        AbortData abort_data;
    } state_data;
    bool gnc_connected;
    float gnc_last_pinged_ns;
    bool daq_connected;
    float daq_last_pinged_ns;
    /* Sensors */
    AnalogSensorReadings analog_sensors;
    /* Time taken by various controller components. */
    ControllerTiming controller_timing;
} DataPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ClientType_MIN ClientType_UNKNOWN_CLIENT
#define _ClientType_MAX ClientType_DAQ
#define _ClientType_ARRAYSIZE ((ClientType)(ClientType_DAQ+1))

#define _TCType_MIN TCType_UNKNOWN_TC_TYPE
#define _TCType_MAX TCType_T_TYPE
#define _TCType_ARRAYSIZE ((TCType)(TCType_T_TYPE+1))

#define _AnalogSensor_MIN AnalogSensor_UNKNOWN_ANALOG_SENSOR
#define _AnalogSensor_MAX AnalogSensor_BATTERY_VOLTAGE
#define _AnalogSensor_ARRAYSIZE ((AnalogSensor)(AnalogSensor_BATTERY_VOLTAGE+1))

#define _Valve_MIN Valve_UNKNOWN_VALVE
#define _Valve_MAX Valve_LOX
#define _Valve_ARRAYSIZE ((Valve)(Valve_LOX+1))

#define _SystemState_MIN SystemState_STATE_UNKNOWN
#define _SystemState_MAX SystemState_STATE_ABORT
#define _SystemState_ARRAYSIZE ((SystemState)(SystemState_STATE_ABORT+1))





#define IdentifyClientRequest_client_ENUMTYPE ClientType


#define AnalogSensorConfig_assignment_ENUMTYPE AnalogSensor
#define AnalogSensorConfig_tc_type_ENUMTYPE TCType

#define ResetValvePositionRequest_valve_ENUMTYPE Valve

#define PowerOnValveRequest_valve_ENUMTYPE Valve

#define PowerOffValveRequest_valve_ENUMTYPE Valve




#define CalibrateValveRequest_valve_ENUMTYPE Valve









#define DataPacket_state_ENUMTYPE SystemState










/* Initializer values for message structs */
#define Request_init_default                     {0, {SubscribeDataStreamRequest_init_default}}
#define Response_init_default                    {{{NULL}, NULL}}
#define SubscribeDataStreamRequest_init_default  {0}
#define IsNotAbortedRequest_init_default         {0}
#define IdentifyClientRequest_init_default       {_ClientType_MIN}
#define ConfigureAnalogSensorsRequest_init_default {{{NULL}, NULL}}
#define AnalogSensorConfig_init_default          {0, _AnalogSensor_MIN, false, 0, false, 0, false, _TCType_MIN, false, 0, false, 0}
#define ResetValvePositionRequest_init_default   {_Valve_MIN, 0}
#define PowerOnValveRequest_init_default         {_Valve_MIN}
#define PowerOffValveRequest_init_default        {_Valve_MIN}
#define AbortRequest_init_default                {0}
#define HaltRequest_init_default                 {0}
#define UnprimeRequest_init_default              {0}
#define CalibrateValveRequest_init_default       {_Valve_MIN}
#define LoadValveSequenceRequest_init_default    {false, ControlTrace_init_default, false, ControlTrace_init_default}
#define StartValveSequenceRequest_init_default   {0}
#define LoadThrustSequenceRequest_init_default   {ControlTrace_init_default}
#define StartThrustSequenceRequest_init_default  {0}
#define ControlTrace_init_default                {0, {{NULL}, NULL}}
#define Segment_init_default                     {0, 0, 0, {LinearSegment_init_default}}
#define LinearSegment_init_default               {0, 0}
#define SineSegment_init_default                 {0, 0, 0, 0}
#define DataPacket_init_default                  {0, 0, ValveStatus_init_default, ValveStatus_init_default, _SystemState_MIN, 0, 0, {ValveCalibrationData_init_default}, 0, 0, 0, 0, AnalogSensorReadings_init_default, ControllerTiming_init_default}
#define ControllerTiming_init_default            {0, 0, 0}
#define ValveStatus_init_default                 {0, 0, 0, 0}
#define AnalogSensorReadings_init_default        {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define IdleData_init_default                    {0}
#define AbortData_init_default                   {0}
#define ValveCalibrationData_init_default        {0, 0, 0, 0, 0, 0, 0, 0}
#define ValveSequenceData_init_default           {0}
#define ThrustSequenceData_init_default          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Request_init_zero                        {0, {SubscribeDataStreamRequest_init_zero}}
#define Response_init_zero                       {{{NULL}, NULL}}
#define SubscribeDataStreamRequest_init_zero     {0}
#define IsNotAbortedRequest_init_zero            {0}
#define IdentifyClientRequest_init_zero          {_ClientType_MIN}
#define ConfigureAnalogSensorsRequest_init_zero  {{{NULL}, NULL}}
#define AnalogSensorConfig_init_zero             {0, _AnalogSensor_MIN, false, 0, false, 0, false, _TCType_MIN, false, 0, false, 0}
#define ResetValvePositionRequest_init_zero      {_Valve_MIN, 0}
#define PowerOnValveRequest_init_zero            {_Valve_MIN}
#define PowerOffValveRequest_init_zero           {_Valve_MIN}
#define AbortRequest_init_zero                   {0}
#define HaltRequest_init_zero                    {0}
#define UnprimeRequest_init_zero                 {0}
#define CalibrateValveRequest_init_zero          {_Valve_MIN}
#define LoadValveSequenceRequest_init_zero       {false, ControlTrace_init_zero, false, ControlTrace_init_zero}
#define StartValveSequenceRequest_init_zero      {0}
#define LoadThrustSequenceRequest_init_zero      {ControlTrace_init_zero}
#define StartThrustSequenceRequest_init_zero     {0}
#define ControlTrace_init_zero                   {0, {{NULL}, NULL}}
#define Segment_init_zero                        {0, 0, 0, {LinearSegment_init_zero}}
#define LinearSegment_init_zero                  {0, 0}
#define SineSegment_init_zero                    {0, 0, 0, 0}
#define DataPacket_init_zero                     {0, 0, ValveStatus_init_zero, ValveStatus_init_zero, _SystemState_MIN, 0, 0, {ValveCalibrationData_init_zero}, 0, 0, 0, 0, AnalogSensorReadings_init_zero, ControllerTiming_init_zero}
#define ControllerTiming_init_zero               {0, 0, 0}
#define ValveStatus_init_zero                    {0, 0, 0, 0}
#define AnalogSensorReadings_init_zero           {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define IdleData_init_zero                       {0}
#define AbortData_init_zero                      {0}
#define ValveCalibrationData_init_zero           {0, 0, 0, 0, 0, 0, 0, 0}
#define ValveSequenceData_init_zero              {0}
#define ThrustSequenceData_init_zero             {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Response_err_tag                         1
#define IdentifyClientRequest_client_tag         1
#define ConfigureAnalogSensorsRequest_configs_tag 1
#define AnalogSensorConfig_channel_tag           1
#define AnalogSensorConfig_assignment_tag        2
#define AnalogSensorConfig_pt_range_psig_tag     3
#define AnalogSensorConfig_pt_bias_psig_tag      4
#define AnalogSensorConfig_tc_type_tag           5
#define AnalogSensorConfig_raw_range_v_tag       6
#define AnalogSensorConfig_raw_bias_v_tag        7
#define ResetValvePositionRequest_valve_tag      1
#define ResetValvePositionRequest_new_pos_deg_tag 2
#define PowerOnValveRequest_valve_tag            1
#define PowerOffValveRequest_valve_tag           1
#define CalibrateValveRequest_valve_tag          1
#define ControlTrace_total_time_ms_tag           1
#define ControlTrace_segments_tag                2
#define LoadValveSequenceRequest_fuel_trace_deg_tag 1
#define LoadValveSequenceRequest_lox_trace_deg_tag 2
#define LoadThrustSequenceRequest_thrust_trace_lbf_tag 1
#define Request_subscribe_data_stream_tag        1
#define Request_reset_valve_position_tag         2
#define Request_identify_client_tag              6
#define Request_calibrate_valve_tag              9
#define Request_abort_tag                        10
#define Request_halt_tag                         11
#define Request_unprime_tag                      12
#define Request_load_valve_sequence_tag          13
#define Request_load_thrust_sequence_tag         14
#define Request_start_valve_sequence_tag         15
#define Request_start_thrust_sequence_tag        16
#define Request_power_off_valve_tag              18
#define Request_power_on_valve_tag               19
#define Request_is_not_aborted_request_tag       20
#define Request_configure_analog_sensors_tag     21
#define LinearSegment_start_val_tag              1
#define LinearSegment_end_val_tag                2
#define SineSegment_offset_tag                   1
#define SineSegment_amplitude_tag                2
#define SineSegment_period_tag                   3
#define SineSegment_phase_deg_tag                4
#define Segment_start_ms_tag                     1
#define Segment_length_ms_tag                    2
#define Segment_linear_tag                       3
#define Segment_sine_tag                         4
#define ControllerTiming_controller_tick_time_ns_tag 1
#define ControllerTiming_analog_sensors_sense_time_ns_tag 2
#define ControllerTiming_lidar_sense_time_ns_tag 3
#define ValveStatus_target_pos_deg_tag           1
#define ValveStatus_driver_setpoint_pos_deg_tag  2
#define ValveStatus_encoder_pos_deg_tag          3
#define ValveStatus_is_on_tag                    4
#define AnalogSensorReadings_pt001_tag           1
#define AnalogSensorReadings_pt002_tag           2
#define AnalogSensorReadings_pt003_tag           3
#define AnalogSensorReadings_pt004_tag           4
#define AnalogSensorReadings_pt005_tag           5
#define AnalogSensorReadings_pt101_tag           6
#define AnalogSensorReadings_pt201_tag           7
#define AnalogSensorReadings_ptf1_tag            8
#define AnalogSensorReadings_ptf2_tag            9
#define AnalogSensorReadings_pto1_tag            10
#define AnalogSensorReadings_ptc1_tag            11
#define AnalogSensorReadings_ptc2_tag            12
#define AnalogSensorReadings_tc001_tag           13
#define AnalogSensorReadings_tc101_tag           14
#define AnalogSensorReadings_tc102_tag           15
#define AnalogSensorReadings_tcf1_tag            16
#define AnalogSensorReadings_tco1_tag            17
#define AnalogSensorReadings_ptg001_tag          18
#define AnalogSensorReadings_ptg002_tag          19
#define AnalogSensorReadings_ptg101_tag          20
#define AnalogSensorReadings_battery_voltage_tag 21
#define ValveCalibrationData_fuel_found_hardstop_tag 3
#define ValveCalibrationData_fuel_hardstop_pos_tag 4
#define ValveCalibrationData_lox_found_hardstop_tag 7
#define ValveCalibrationData_lox_hardstop_pos_tag 8
#define ValveCalibrationData_cal_phase_tag       9
#define ValveCalibrationData_rep_count_tag       10
#define ValveCalibrationData_fuel_err_tag        11
#define ValveCalibrationData_lox_err_tag         12
#define ThrustSequenceData_predicted_thrust_tag  1
#define ThrustSequenceData_predicted_of_tag      2
#define ThrustSequenceData_mdot_fuel_tag         3
#define ThrustSequenceData_mdot_lox_tag          4
#define ThrustSequenceData_target_thrust_tag     5
#define ThrustSequenceData_thrust_error_tag      6
#define ThrustSequenceData_change_alpha_cmd_tag  7
#define ThrustSequenceData_clamped_change_alpha_cmd_tag 8
#define ThrustSequenceData_alpha_tag             9
#define ThrustSequenceData_thrust_from_alpha_tag 10
#define ThrustSequenceData_fuel_valve_cmd_tag    11
#define ThrustSequenceData_lox_valve_cmd_tag     12
#define DataPacket_time_ns_tag                   1
#define DataPacket_data_queue_size_tag           2
#define DataPacket_fuel_valve_tag                3
#define DataPacket_lox_valve_tag                 4
#define DataPacket_state_tag                     6
#define DataPacket_sequence_number_tag           8
#define DataPacket_valve_calibration_data_tag    9
#define DataPacket_valve_sequence_data_tag       10
#define DataPacket_thrust_sequence_data_tag      11
#define DataPacket_idle_data_tag                 13
#define DataPacket_abort_data_tag                14
#define DataPacket_gnc_connected_tag             15
#define DataPacket_gnc_last_pinged_ns_tag        16
#define DataPacket_daq_connected_tag             17
#define DataPacket_daq_last_pinged_ns_tag        18
#define DataPacket_analog_sensors_tag            19
#define DataPacket_controller_timing_tag         20

/* Struct field encoding specification for nanopb */
#define Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,subscribe_data_stream,payload.subscribe_data_stream),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,reset_valve_position,payload.reset_valve_position),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,identify_client,payload.identify_client),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,calibrate_valve,payload.calibrate_valve),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,abort,payload.abort),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,halt,payload.halt),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,unprime,payload.unprime),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,load_valve_sequence,payload.load_valve_sequence),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,load_thrust_sequence,payload.load_thrust_sequence),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,start_valve_sequence,payload.start_valve_sequence),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,start_thrust_sequence,payload.start_thrust_sequence),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,power_off_valve,payload.power_off_valve),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,power_on_valve,payload.power_on_valve),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,is_not_aborted_request,payload.is_not_aborted_request),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,configure_analog_sensors,payload.configure_analog_sensors),  21)
#define Request_CALLBACK NULL
#define Request_DEFAULT NULL
#define Request_payload_subscribe_data_stream_MSGTYPE SubscribeDataStreamRequest
#define Request_payload_reset_valve_position_MSGTYPE ResetValvePositionRequest
#define Request_payload_identify_client_MSGTYPE IdentifyClientRequest
#define Request_payload_calibrate_valve_MSGTYPE CalibrateValveRequest
#define Request_payload_abort_MSGTYPE AbortRequest
#define Request_payload_halt_MSGTYPE HaltRequest
#define Request_payload_unprime_MSGTYPE UnprimeRequest
#define Request_payload_load_valve_sequence_MSGTYPE LoadValveSequenceRequest
#define Request_payload_load_thrust_sequence_MSGTYPE LoadThrustSequenceRequest
#define Request_payload_start_valve_sequence_MSGTYPE StartValveSequenceRequest
#define Request_payload_start_thrust_sequence_MSGTYPE StartThrustSequenceRequest
#define Request_payload_power_off_valve_MSGTYPE PowerOffValveRequest
#define Request_payload_power_on_valve_MSGTYPE PowerOnValveRequest
#define Request_payload_is_not_aborted_request_MSGTYPE IsNotAbortedRequest
#define Request_payload_configure_analog_sensors_MSGTYPE ConfigureAnalogSensorsRequest

#define Response_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   err,               1)
#define Response_CALLBACK pb_default_field_callback
#define Response_DEFAULT NULL

#define SubscribeDataStreamRequest_FIELDLIST(X, a) \

#define SubscribeDataStreamRequest_CALLBACK NULL
#define SubscribeDataStreamRequest_DEFAULT NULL

#define IsNotAbortedRequest_FIELDLIST(X, a) \

#define IsNotAbortedRequest_CALLBACK NULL
#define IsNotAbortedRequest_DEFAULT NULL

#define IdentifyClientRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    client,            1)
#define IdentifyClientRequest_CALLBACK NULL
#define IdentifyClientRequest_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

#define ConfigureAnalogSensorsRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  configs,           1)
#define ConfigureAnalogSensorsRequest_CALLBACK pb_default_field_callback
#define ConfigureAnalogSensorsRequest_DEFAULT NULL
#define ConfigureAnalogSensorsRequest_configs_MSGTYPE AnalogSensorConfig

#define AnalogSensorConfig_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   channel,           1) \
X(a, STATIC,   REQUIRED, UENUM,    assignment,        2) \
X(a, STATIC,   OPTIONAL, FLOAT,    pt_range_psig,     3) \
X(a, STATIC,   OPTIONAL, FLOAT,    pt_bias_psig,      4) \
X(a, STATIC,   OPTIONAL, UENUM,    tc_type,           5) \
X(a, STATIC,   OPTIONAL, FLOAT,    raw_range_v,       6) \
X(a, STATIC,   OPTIONAL, FLOAT,    raw_bias_v,        7)
#define AnalogSensorConfig_CALLBACK NULL
#define AnalogSensorConfig_DEFAULT NULL

#define ResetValvePositionRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    valve,             1) \
X(a, STATIC,   REQUIRED, FLOAT,    new_pos_deg,       2)
#define ResetValvePositionRequest_CALLBACK NULL
#define ResetValvePositionRequest_DEFAULT NULL

#define PowerOnValveRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    valve,             1)
#define PowerOnValveRequest_CALLBACK NULL
#define PowerOnValveRequest_DEFAULT NULL

#define PowerOffValveRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    valve,             1)
#define PowerOffValveRequest_CALLBACK NULL
#define PowerOffValveRequest_DEFAULT NULL

#define AbortRequest_FIELDLIST(X, a) \

#define AbortRequest_CALLBACK NULL
#define AbortRequest_DEFAULT NULL

#define HaltRequest_FIELDLIST(X, a) \

#define HaltRequest_CALLBACK NULL
#define HaltRequest_DEFAULT NULL

#define UnprimeRequest_FIELDLIST(X, a) \

#define UnprimeRequest_CALLBACK NULL
#define UnprimeRequest_DEFAULT NULL

#define CalibrateValveRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    valve,             1)
#define CalibrateValveRequest_CALLBACK NULL
#define CalibrateValveRequest_DEFAULT NULL

#define LoadValveSequenceRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fuel_trace_deg,    1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lox_trace_deg,     2)
#define LoadValveSequenceRequest_CALLBACK NULL
#define LoadValveSequenceRequest_DEFAULT NULL
#define LoadValveSequenceRequest_fuel_trace_deg_MSGTYPE ControlTrace
#define LoadValveSequenceRequest_lox_trace_deg_MSGTYPE ControlTrace

#define StartValveSequenceRequest_FIELDLIST(X, a) \

#define StartValveSequenceRequest_CALLBACK NULL
#define StartValveSequenceRequest_DEFAULT NULL

#define LoadThrustSequenceRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  thrust_trace_lbf,   1)
#define LoadThrustSequenceRequest_CALLBACK NULL
#define LoadThrustSequenceRequest_DEFAULT NULL
#define LoadThrustSequenceRequest_thrust_trace_lbf_MSGTYPE ControlTrace

#define StartThrustSequenceRequest_FIELDLIST(X, a) \

#define StartThrustSequenceRequest_CALLBACK NULL
#define StartThrustSequenceRequest_DEFAULT NULL

#define ControlTrace_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   total_time_ms,     1) \
X(a, CALLBACK, REPEATED, MESSAGE,  segments,          2)
#define ControlTrace_CALLBACK pb_default_field_callback
#define ControlTrace_DEFAULT NULL
#define ControlTrace_segments_MSGTYPE Segment

#define Segment_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   start_ms,          1) \
X(a, STATIC,   REQUIRED, UINT32,   length_ms,         2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,linear,type.linear),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,sine,type.sine),   4)
#define Segment_CALLBACK NULL
#define Segment_DEFAULT NULL
#define Segment_type_linear_MSGTYPE LinearSegment
#define Segment_type_sine_MSGTYPE SineSegment

#define LinearSegment_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    start_val,         1) \
X(a, STATIC,   REQUIRED, FLOAT,    end_val,           2)
#define LinearSegment_CALLBACK NULL
#define LinearSegment_DEFAULT NULL

#define SineSegment_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    offset,            1) \
X(a, STATIC,   REQUIRED, FLOAT,    amplitude,         2) \
X(a, STATIC,   REQUIRED, FLOAT,    period,            3) \
X(a, STATIC,   REQUIRED, FLOAT,    phase_deg,         4)
#define SineSegment_CALLBACK NULL
#define SineSegment_DEFAULT NULL

#define DataPacket_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   time_ns,           1) \
X(a, STATIC,   REQUIRED, UINT32,   data_queue_size,   2) \
X(a, STATIC,   REQUIRED, MESSAGE,  fuel_valve,        3) \
X(a, STATIC,   REQUIRED, MESSAGE,  lox_valve,         4) \
X(a, STATIC,   REQUIRED, UENUM,    state,             6) \
X(a, STATIC,   REQUIRED, UINT64,   sequence_number,   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (state_data,valve_calibration_data,state_data.valve_calibration_data),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (state_data,valve_sequence_data,state_data.valve_sequence_data),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (state_data,thrust_sequence_data,state_data.thrust_sequence_data),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (state_data,idle_data,state_data.idle_data),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (state_data,abort_data,state_data.abort_data),  14) \
X(a, STATIC,   REQUIRED, BOOL,     gnc_connected,    15) \
X(a, STATIC,   REQUIRED, FLOAT,    gnc_last_pinged_ns,  16) \
X(a, STATIC,   REQUIRED, BOOL,     daq_connected,    17) \
X(a, STATIC,   REQUIRED, FLOAT,    daq_last_pinged_ns,  18) \
X(a, STATIC,   REQUIRED, MESSAGE,  analog_sensors,   19) \
X(a, STATIC,   REQUIRED, MESSAGE,  controller_timing,  20)
#define DataPacket_CALLBACK NULL
#define DataPacket_DEFAULT NULL
#define DataPacket_fuel_valve_MSGTYPE ValveStatus
#define DataPacket_lox_valve_MSGTYPE ValveStatus
#define DataPacket_state_data_valve_calibration_data_MSGTYPE ValveCalibrationData
#define DataPacket_state_data_valve_sequence_data_MSGTYPE ValveSequenceData
#define DataPacket_state_data_thrust_sequence_data_MSGTYPE ThrustSequenceData
#define DataPacket_state_data_idle_data_MSGTYPE IdleData
#define DataPacket_state_data_abort_data_MSGTYPE AbortData
#define DataPacket_analog_sensors_MSGTYPE AnalogSensorReadings
#define DataPacket_controller_timing_MSGTYPE ControllerTiming

#define ControllerTiming_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    controller_tick_time_ns,   1) \
X(a, STATIC,   REQUIRED, FLOAT,    analog_sensors_sense_time_ns,   2) \
X(a, STATIC,   REQUIRED, FLOAT,    lidar_sense_time_ns,   3)
#define ControllerTiming_CALLBACK NULL
#define ControllerTiming_DEFAULT NULL

#define ValveStatus_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    target_pos_deg,    1) \
X(a, STATIC,   REQUIRED, FLOAT,    driver_setpoint_pos_deg,   2) \
X(a, STATIC,   REQUIRED, FLOAT,    encoder_pos_deg,   3) \
X(a, STATIC,   REQUIRED, BOOL,     is_on,             4)
#define ValveStatus_CALLBACK NULL
#define ValveStatus_DEFAULT NULL

#define AnalogSensorReadings_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    pt001,             1) \
X(a, STATIC,   OPTIONAL, FLOAT,    pt002,             2) \
X(a, STATIC,   OPTIONAL, FLOAT,    pt003,             3) \
X(a, STATIC,   OPTIONAL, FLOAT,    pt004,             4) \
X(a, STATIC,   OPTIONAL, FLOAT,    pt005,             5) \
X(a, STATIC,   OPTIONAL, FLOAT,    pt101,             6) \
X(a, STATIC,   OPTIONAL, FLOAT,    pt201,             7) \
X(a, STATIC,   OPTIONAL, FLOAT,    ptf1,              8) \
X(a, STATIC,   OPTIONAL, FLOAT,    ptf2,              9) \
X(a, STATIC,   OPTIONAL, FLOAT,    pto1,             10) \
X(a, STATIC,   OPTIONAL, FLOAT,    ptc1,             11) \
X(a, STATIC,   OPTIONAL, FLOAT,    ptc2,             12) \
X(a, STATIC,   OPTIONAL, FLOAT,    tc001,            13) \
X(a, STATIC,   OPTIONAL, FLOAT,    tc101,            14) \
X(a, STATIC,   OPTIONAL, FLOAT,    tc102,            15) \
X(a, STATIC,   OPTIONAL, FLOAT,    tcf1,             16) \
X(a, STATIC,   OPTIONAL, FLOAT,    tco1,             17) \
X(a, STATIC,   OPTIONAL, FLOAT,    ptg001,           18) \
X(a, STATIC,   OPTIONAL, FLOAT,    ptg002,           19) \
X(a, STATIC,   OPTIONAL, FLOAT,    ptg101,           20) \
X(a, STATIC,   OPTIONAL, FLOAT,    battery_voltage,  21)
#define AnalogSensorReadings_CALLBACK NULL
#define AnalogSensorReadings_DEFAULT NULL

#define IdleData_FIELDLIST(X, a) \

#define IdleData_CALLBACK NULL
#define IdleData_DEFAULT NULL

#define AbortData_FIELDLIST(X, a) \

#define AbortData_CALLBACK NULL
#define AbortData_DEFAULT NULL

#define ValveCalibrationData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     fuel_found_hardstop,   3) \
X(a, STATIC,   REQUIRED, FLOAT,    fuel_hardstop_pos,   4) \
X(a, STATIC,   REQUIRED, BOOL,     lox_found_hardstop,   7) \
X(a, STATIC,   REQUIRED, FLOAT,    lox_hardstop_pos,   8) \
X(a, STATIC,   REQUIRED, INT32,    cal_phase,         9) \
X(a, STATIC,   REQUIRED, INT32,    rep_count,        10) \
X(a, STATIC,   REQUIRED, FLOAT,    fuel_err,         11) \
X(a, STATIC,   REQUIRED, FLOAT,    lox_err,          12)
#define ValveCalibrationData_CALLBACK NULL
#define ValveCalibrationData_DEFAULT NULL

#define ValveSequenceData_FIELDLIST(X, a) \

#define ValveSequenceData_CALLBACK NULL
#define ValveSequenceData_DEFAULT NULL

#define ThrustSequenceData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    predicted_thrust,   1) \
X(a, STATIC,   REQUIRED, FLOAT,    predicted_of,      2) \
X(a, STATIC,   REQUIRED, FLOAT,    mdot_fuel,         3) \
X(a, STATIC,   REQUIRED, FLOAT,    mdot_lox,          4) \
X(a, STATIC,   REQUIRED, FLOAT,    target_thrust,     5) \
X(a, STATIC,   REQUIRED, FLOAT,    thrust_error,      6) \
X(a, STATIC,   REQUIRED, FLOAT,    change_alpha_cmd,   7) \
X(a, STATIC,   REQUIRED, FLOAT,    clamped_change_alpha_cmd,   8) \
X(a, STATIC,   REQUIRED, FLOAT,    alpha,             9) \
X(a, STATIC,   REQUIRED, FLOAT,    thrust_from_alpha,  10) \
X(a, STATIC,   REQUIRED, FLOAT,    fuel_valve_cmd,   11) \
X(a, STATIC,   REQUIRED, FLOAT,    lox_valve_cmd,    12)
#define ThrustSequenceData_CALLBACK NULL
#define ThrustSequenceData_DEFAULT NULL

extern const pb_msgdesc_t Request_msg;
extern const pb_msgdesc_t Response_msg;
extern const pb_msgdesc_t SubscribeDataStreamRequest_msg;
extern const pb_msgdesc_t IsNotAbortedRequest_msg;
extern const pb_msgdesc_t IdentifyClientRequest_msg;
extern const pb_msgdesc_t ConfigureAnalogSensorsRequest_msg;
extern const pb_msgdesc_t AnalogSensorConfig_msg;
extern const pb_msgdesc_t ResetValvePositionRequest_msg;
extern const pb_msgdesc_t PowerOnValveRequest_msg;
extern const pb_msgdesc_t PowerOffValveRequest_msg;
extern const pb_msgdesc_t AbortRequest_msg;
extern const pb_msgdesc_t HaltRequest_msg;
extern const pb_msgdesc_t UnprimeRequest_msg;
extern const pb_msgdesc_t CalibrateValveRequest_msg;
extern const pb_msgdesc_t LoadValveSequenceRequest_msg;
extern const pb_msgdesc_t StartValveSequenceRequest_msg;
extern const pb_msgdesc_t LoadThrustSequenceRequest_msg;
extern const pb_msgdesc_t StartThrustSequenceRequest_msg;
extern const pb_msgdesc_t ControlTrace_msg;
extern const pb_msgdesc_t Segment_msg;
extern const pb_msgdesc_t LinearSegment_msg;
extern const pb_msgdesc_t SineSegment_msg;
extern const pb_msgdesc_t DataPacket_msg;
extern const pb_msgdesc_t ControllerTiming_msg;
extern const pb_msgdesc_t ValveStatus_msg;
extern const pb_msgdesc_t AnalogSensorReadings_msg;
extern const pb_msgdesc_t IdleData_msg;
extern const pb_msgdesc_t AbortData_msg;
extern const pb_msgdesc_t ValveCalibrationData_msg;
extern const pb_msgdesc_t ValveSequenceData_msg;
extern const pb_msgdesc_t ThrustSequenceData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Request_fields &Request_msg
#define Response_fields &Response_msg
#define SubscribeDataStreamRequest_fields &SubscribeDataStreamRequest_msg
#define IsNotAbortedRequest_fields &IsNotAbortedRequest_msg
#define IdentifyClientRequest_fields &IdentifyClientRequest_msg
#define ConfigureAnalogSensorsRequest_fields &ConfigureAnalogSensorsRequest_msg
#define AnalogSensorConfig_fields &AnalogSensorConfig_msg
#define ResetValvePositionRequest_fields &ResetValvePositionRequest_msg
#define PowerOnValveRequest_fields &PowerOnValveRequest_msg
#define PowerOffValveRequest_fields &PowerOffValveRequest_msg
#define AbortRequest_fields &AbortRequest_msg
#define HaltRequest_fields &HaltRequest_msg
#define UnprimeRequest_fields &UnprimeRequest_msg
#define CalibrateValveRequest_fields &CalibrateValveRequest_msg
#define LoadValveSequenceRequest_fields &LoadValveSequenceRequest_msg
#define StartValveSequenceRequest_fields &StartValveSequenceRequest_msg
#define LoadThrustSequenceRequest_fields &LoadThrustSequenceRequest_msg
#define StartThrustSequenceRequest_fields &StartThrustSequenceRequest_msg
#define ControlTrace_fields &ControlTrace_msg
#define Segment_fields &Segment_msg
#define LinearSegment_fields &LinearSegment_msg
#define SineSegment_fields &SineSegment_msg
#define DataPacket_fields &DataPacket_msg
#define ControllerTiming_fields &ControllerTiming_msg
#define ValveStatus_fields &ValveStatus_msg
#define AnalogSensorReadings_fields &AnalogSensorReadings_msg
#define IdleData_fields &IdleData_msg
#define AbortData_fields &AbortData_msg
#define ValveCalibrationData_fields &ValveCalibrationData_msg
#define ValveSequenceData_fields &ValveSequenceData_msg
#define ThrustSequenceData_fields &ThrustSequenceData_msg

/* Maximum encoded size of messages (where known) */
/* Request_size depends on runtime parameters */
/* Response_size depends on runtime parameters */
/* ConfigureAnalogSensorsRequest_size depends on runtime parameters */
/* LoadValveSequenceRequest_size depends on runtime parameters */
/* LoadThrustSequenceRequest_size depends on runtime parameters */
/* ControlTrace_size depends on runtime parameters */
#define AbortData_size                           0
#define AbortRequest_size                        0
#define AnalogSensorConfig_size                  30
#define AnalogSensorReadings_size                111
#define CLOVER_PB_H_MAX_SIZE                     DataPacket_size
#define CalibrateValveRequest_size               2
#define ControllerTiming_size                    15
#define DataPacket_size                          279
#define HaltRequest_size                         0
#define IdentifyClientRequest_size               2
#define IdleData_size                            0
#define IsNotAbortedRequest_size                 0
#define LinearSegment_size                       10
#define PowerOffValveRequest_size                2
#define PowerOnValveRequest_size                 2
#define ResetValvePositionRequest_size           7
#define Segment_size                             34
#define SineSegment_size                         20
#define StartThrustSequenceRequest_size          0
#define StartValveSequenceRequest_size           0
#define SubscribeDataStreamRequest_size          0
#define ThrustSequenceData_size                  60
#define UnprimeRequest_size                      0
#define ValveCalibrationData_size                46
#define ValveSequenceData_size                   0
#define ValveStatus_size                         17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
