#ifndef APP_CONTROLLER_CONFIG_H
#define APP_CONTROLLER_CONFIG_H

constexpr uint64_t NSEC_PER_CONTROL_TICK = 1'000'000; // 1 ms
constexpr float SEC_PER_CONTROL_TICK = NSEC_PER_CONTROL_TICK * 1e-9f;

#endif // APP_CONTROLLER_CONFIG_H
