# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flasherd.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'flasherd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66lasherd.proto\x12\x08\x66lasherd\"G\n\x03\x41rg\x12\x14\n\x07regular\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06\x62inary\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_regularB\t\n\x07_binary\"\xb2\x02\n\x11RunCommandRequest\x12\x1c\n\x0f\x63ommand_windows\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1a\n\rcommand_macos\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1a\n\rcommand_linux\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1b\n\x04\x61rgs\x18\x04 \x03(\x0b\x32\r.flasherd.Arg\x12\x12\n\x05stdin\x18\x05 \x01(\x0cH\x03\x88\x01\x01\x12\x18\n\x0b\x62inary_name\x18\x06 \x01(\tH\x04\x88\x01\x01\x12\x19\n\x0c\x62inary_chunk\x18\x07 \x01(\x0cH\x05\x88\x01\x01\x42\x12\n\x10_command_windowsB\x10\n\x0e_command_macosB\x10\n\x0e_command_linuxB\x08\n\x06_stdinB\x0e\n\x0c_binary_nameB\x0f\n\r_binary_chunk\"z\n\x12RunCommandResponse\x12\x16\n\texit_code\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x13\n\x06stdout\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12\x13\n\x06stderr\x18\x03 \x01(\x0cH\x02\x88\x01\x01\x42\x0c\n\n_exit_codeB\t\n\x07_stdoutB\t\n\x07_stderr2W\n\x08\x46lasherd\x12K\n\nRunCommand\x12\x1b.flasherd.RunCommandRequest\x1a\x1c.flasherd.RunCommandResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flasherd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARG']._serialized_start=28
  _globals['_ARG']._serialized_end=99
  _globals['_RUNCOMMANDREQUEST']._serialized_start=102
  _globals['_RUNCOMMANDREQUEST']._serialized_end=408
  _globals['_RUNCOMMANDRESPONSE']._serialized_start=410
  _globals['_RUNCOMMANDRESPONSE']._serialized_end=532
  _globals['_FLASHERD']._serialized_start=534
  _globals['_FLASHERD']._serialized_end=621
# @@protoc_insertion_point(module_scope)
