fuel_trace_deg {
  total_time_ms: 1000
  segments {
    start_ms: 0
    length_ms: 1000
    linear {
      start_val: 50.0
      end_val: 0.0
    }
  }
}
lox_trace_deg {
  total_time_ms: 1000
  segments {
    start_ms: 0
    length_ms: 1000
    linear {
      start_val: 50.0
      end_val: 0.0
    }
  }
}
