# Basic System Configuration
CONFIG_SERIAL=n
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=n

# Enable ADC and SPI Framework
CONFIG_ADC=y
CONFIG_SPI=y
CONFIG_GPIO=y

# TI ADS7953 Driver (ADS79xx Series)
CONFIG_ADC_ADS79XX=y

# RTT Debugging (Alternative to UART for viewing adc_read results)
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=y
