#!/bin/bash

set -euo pipefail
source /home/lpl/arty/credentials

set -euxo pipefail

DOCKER_HOST="tcp://localhost:2375"

# Check for uncommitted changes
if [[ -n "$(git status -s)" ]]; then
    echo "You have uncommitted changes, please commit everything before running this script."
    exit 1
fi

# Ensure we are on a dev branch
curr_branch="$(git branch --show-current)"
if [[ "$curr_branch" == "main" ]]; then
    echo "The current branch is main, ensure you are on a non-main branch before running this script so we can make a PR."
    exit 1
elif [[ -z "$curr_branch" ]]; then
    echo "There is no current branch; ensure you are on one so we can auto-push changes."
    exit 1
fi

image_tag="ghcr.io/lpl-daq/arty/dev-container:build_$(date '+%Y-%m-%d_%H-%M-%S')_$(git rev-parse HEAD)"

# Build image
docker build ~/arty --platform linux/amd64 -t "$image_tag" "$@"

# Push to ghcr
echo "$GITHUB_PERSONAL_ACCESS_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
docker image push "$image_tag"

# Show image details
docker image ls "$image_tag"

# Reference new image from dev container config
jq ".image = \"$image_tag\" | del(.build) | .initializeCommand = \"docker image pull --platform=linux/amd64 $image_tag\"" .devcontainer.json | tee /home/lpl/arty/.devcontainer.json.temp
mv /home/lpl/arty/.devcontainer.json.temp /home/lpl/arty/.devcontainer.json

# Commit changes
git add /home/lpl/arty/.devcontainer.json
git commit -m "[autogenerated] Update dev container image to $image_tag"
git push -u origin "$curr_branch"
